spring.application.name=lab3

# Redis Direct Connection (Docker Desktop WSL2 环境下哨兵返回容器内部 IP，宿主机不可达，故使用直连)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Lettuce Connection Pool
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=2
spring.data.redis.lettuce.pool.max-wait=-1ms
